-- API Datasource table
CREATE TABLE IF NOT EXISTS FLW_API_DATASOURCE (
    ID_ BIGSERIAL PRIMARY KEY,
    KEY_ VARCHAR(255) NOT NULL,
    VERSION_ INTEGER NOT NULL,
    TYPE_ VARCHAR(50) NOT NULL,
    STATUS_ VARCHAR(50) NOT NULL,
    NAME_ VARCHAR(255) NOT NULL,
    DESCRIPTION_ TEXT,
    INPUT_SCHEMA_ TEXT,
    OUTPUT_SCHEMA_ TEXT,
    STRICT_ BOOLEAN DEFAULT TRUE,
    OPERATION_ TEXT,
    CONNECTION_ TEXT,
    EXTENSION_ TEXT,
    CREATED_AT_ TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT_ TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (KEY_, VERSION_)
);

-- API Service table
CREATE TABLE IF NOT EXISTS FLW_API_SERVICE (
    ID_ BIGSERIAL PRIMARY KEY,
    KEY_ VARCHAR(255) UNIQUE NOT NULL,
    NAME_ VARCHAR(255) NOT NULL,
    DESCRIPTION_ TEXT,
    DATASOURCE_KEY_ VARCHAR(255) NOT NULL,
    DATASOURCE_VERSION_ INTEGER NOT NULL,
    INPUT_MAPPING_ TEXT,
    OUTPUT_MAPPING_ TEXT,
    CREATED_AT_ TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT_ TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DATASOURCE_KEY_, DATASOURCE_VERSION_) REFERENCES FLW_API_DATASOURCE(KEY_, VERSION_) ON DELETE CASCADE
);

-- Workflow table
CREATE TABLE IF NOT EXISTS FLW_WORKFLOW (
    ID_ BIGSERIAL PRIMARY KEY,
    KEY_ VARCHAR(255) NOT NULL,
    VERSION_ INTEGER NOT NULL,
    NAME_ VARCHAR(255) NOT NULL,
    DESCRIPTION_ TEXT,
    STATUS_ VARCHAR(50) NOT NULL,
    NODES_ TEXT,
    CONNECTIONS_ TEXT,
    CONFIG_ TEXT,
    CREATED_AT_ TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT_ TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (KEY_, VERSION_)
);

-- Workflow execution table
CREATE TABLE IF NOT EXISTS FLW_WORKFLOW_EXECUTION (
    ID_ BIGSERIAL PRIMARY KEY,
    EXECUTION_ID_ VARCHAR(255) UNIQUE NOT NULL,
    WORKFLOW_KEY_ VARCHAR(255) NOT NULL,
    WORKFLOW_VERSION_ INTEGER NOT NULL,
    STATUS_ VARCHAR(50) NOT NULL,
    INPUT_ TEXT,
    OUTPUT_ TEXT,
    ERROR_MESSAGE_ TEXT,
    NODE_STATUSES_ TEXT,
    STARTED_AT_ TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FINISHED_AT_ TIMESTAMP,
    DURATION_MS_ BIGINT,
    FOREIGN KEY (WORKFLOW_KEY_, WORKFLOW_VERSION_) REFERENCES FLW_WORKFLOW(KEY_, VERSION_) ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS IDX_FLW_API_DATASOURCE_KEY_VERSION ON FLW_API_DATASOURCE(KEY_, VERSION_);
CREATE INDEX IF NOT EXISTS IDX_FLW_API_DATASOURCE_TYPE ON FLW_API_DATASOURCE(TYPE_);
CREATE INDEX IF NOT EXISTS IDX_FLW_API_DATASOURCE_STATUS ON FLW_API_DATASOURCE(STATUS_);
CREATE INDEX IF NOT EXISTS IDX_FLW_API_SERVICE_KEY ON FLW_API_SERVICE(KEY_);
CREATE INDEX IF NOT EXISTS IDX_FLW_API_SERVICE_DATASOURCE ON FLW_API_SERVICE(DATASOURCE_KEY_, DATASOURCE_VERSION_);
CREATE INDEX IF NOT EXISTS IDX_FLW_WORKFLOW_KEY_VERSION ON FLW_WORKFLOW(KEY_, VERSION_);
CREATE INDEX IF NOT EXISTS IDX_FLW_WORKFLOW_STATUS ON FLW_WORKFLOW(STATUS_);
CREATE INDEX IF NOT EXISTS IDX_FLW_WORKFLOW_EXECUTION_EXECUTION_ID ON FLW_WORKFLOW_EXECUTION(EXECUTION_ID_);
CREATE INDEX IF NOT EXISTS IDX_FLW_WORKFLOW_EXECUTION_WORKFLOW ON FLW_WORKFLOW_EXECUTION(WORKFLOW_KEY_, WORKFLOW_VERSION_);
CREATE INDEX IF NOT EXISTS IDX_FLW_WORKFLOW_EXECUTION_STATUS ON FLW_WORKFLOW_EXECUTION(STATUS_);
