package com.zwtech.flow.domain.shared;

import java.io.Serializable;
import java.util.List;

/**
 * An aggregate root, as described in the DDD book.
 * <p>
 * Aggregate roots are the root of a cluster of domain objects.
 * They are the only objects that can be loaded directly from the repository.
 * All other objects must be loaded through the aggregate root.
 */
public interface AggregateRoot<T> extends Serializable {

    /**
     * Aggregate roots compare by the value of their identity.
     *
     * @param other The other aggregate root.
     * @return <code>true</code> if the given aggregate root's and this aggregate root's identity are the same.
     */
    boolean sameIdentityAs(T other);

    /**
     * Pull all domain events that have been generated by this aggregate root.
     *
     * @return A list of domain events. After calling this method, the list of domain events will be cleared.
     */
    List<Object> pullDomainEvents();

}
