server:
  port: 8080

spring:
  application:
    name: flowapp

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

logging:
  level:
    root: info
    com:
      zwtech: debug
